#!/bin/bash
set -e
case "$1" in
    configure)
        gtk-update-icon-cache -f /usr/share/icons/hicolor/ 2>/dev/null || true
        update-desktop-database /usr/share/applications/ 2>/dev/null || true

        echo "xfce-night-switch installed. Run 'xfce-night-switch-setup' to complete setup."
        ;;
esac
